name: ligo
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9  # Use the exact Python version used in LIGO notebook
  - numpy=1.2
  - matplotlib=3.4
  - scipy=1.7
  - ipykernel=6
  - decorator=5.0
  - pip
  - h5py=3.6
  - pip:
    - some-pip-package==x.y  # if needed
