name: ligo
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9  # Use the exact Python version used in LIGO notebook
  - numpy=2.0
  - matplotlib=3.9
  - scipy=1.13
  - ipykernel=6.29
  - decorator=5.1
  - pip
  - h5py=3.12
